### ISSUE TITLE
"master" is no longer the default git branch in Github

### ISSUE THREAD

**Issue by myspotontheweb** [kapicorp/kapitan#630]
**Describe the bug/feature**

New repositories in github no longer have a default "master" branch. It has been renamed to "main".

**To Reproduce**

1. Configure a remote inventory

Use a newly created repository. 

```
parameters:
  kapitan:
    vars:
      target: ${target_name}
    inventory:
      - type: git
        source: https://github.com/myspotontheweb/kapitan-demo.git
        subdir: inventory/classes
        output_path: classes/
```

2. Run a compile

```
$ kapitan compile --fetch 
[WARNING] Reclass class not found: 'myorg.apps.staging.app1'. Skipped!
[WARNING] Reclass class not found: 'myorg.apps.staging.app1'. Skipped!
Inventory https://github.com/myspotontheweb/kapitan-demo.git: fetching now
Inventory https://github.com/myspotontheweb/kapitan-demo.git: successfully fetched
Unknown (Non-Kapitan) Error occurred
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "multiprocessing/pool.py", line 121, in worker
  File "kapitan/dependency_manager/base.py", line 120, in fetch_git_dependency
  File "git/cmd.py", line 542, in <lambda>
  File "git/cmd.py", line 1005, in _call_process
  File "git/cmd.py", line 822, in execute
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout master
  stderr: 'error: pathspec 'master' did not match any file(s) known to git.'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "kapitan/targets.py", line 108, in compile_targets
  File "kapitan/remoteinventory/fetch.py", line 74, in fetch_inventories
  File "kapitan/remoteinventory/fetch.py", line 74, in <listcomp>
  File "multiprocessing/pool.py", line 748, in next
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout master
  stderr: 'error: pathspec 'master' did not match any file(s) known to git.'


Cmd('git') failed due to: exit code(1)
  cmdline: git checkout master
  stderr: 'error: pathspec 'master' did not match any file(s) known to git.'
```

3. Note the "master" branch is not found

```
'error: pathspec 'master' did not match any file(s) known to git.'
```

This is hard coded in the python code [here](https://github.com/deepmind/kapitan/blob/master/kapitan/dependency_manager/base.py#L120)

**Expected behavior**

Expected Kapitan to download the remote inventory.

** If it's a bug (please complete the following information):**
 - `python --version`:
 - `pip3 --version`: 
 - `Are you using pyenv or virtualenv?`

```
$ which kapitan
/usr/local/bin/kapitan

$ kapitan --version
0.29.3
```

**Additional context**

N/A

**Comment by myspotontheweb** [comment]
**Work-around**

I reverted my repository's default branch from "main" back to "master".

**Comment by AlphaRoy14** [comment]
Hi @myspotontheweb, Thanks for reporting this! Until this is fixed, maybe you can specify `ref: main` in the target files to save yourself the trouble of manually changing the default branch. 
e.g
```yaml
parameters:
  kapitan:
    vars:
      target: ${target_name}
    inventory:
      - type: git
        source: https://github.com/myspotontheweb/kapitan-demo.git
        subdir: inventory/classes
        output_path: classes/
        ref: main
```
