### ISSUE TITLE
NoneType exception when providing empty Keys in the classes

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan#683]
**Describe the bug/feature**
I noticed is a NoneType exception when providing empty Keys in the classes
```yaml
parameters:
  components:
    mysql:
[...]
      config_maps:
        config:

      secrets:
        secrets:
          data:
            mysql-root-password:
              value: ?{plain:targets/${target_name}/mysql-root-password||randomstr:32|base64}
            mysql-password:
              value: ?{plain:targets/${target_name}/mysql-password||randomstr|base64}
```

**To Reproduce**
1. `git clone https://github.com/kapicorp/kapitan-reference.git`
2. Go to file: https://github.com/kapicorp/kapitan-reference/blob/master/inventory/classes/components/mysql.yml
3. Remove content from `config_maps.config`
3. Run `./kapitan compile`

**Expected behavior**
Empty Keys without values get ignored

** If it's a bug (please complete the following information):**
I'm using docker provided by the kapitan-reference repo
https://github.com/kapicorp/kapitan-reference/blob/master/kapitan

**Additional context**
```bash
$ ./kapitan compile
Unknown (Non-Kapitan) Error occurred
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/venv/lib/python3.7/site-packages/kapitan/targets.py", line 463, in compile_target
    input_compiler.compile_obj(comp_obj, ext_vars, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/kapitan/inputs/base.py", line 54, in compile_obj
    self.compile_input_path(input_path, comp_obj, ext_vars, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/kapitan/inputs/base.py", line 76, in compile_input_path
    **kwargs,
  File "/opt/venv/lib/python3.7/site-packages/kapitan/inputs/kadet.py", line 120, in compile_file
    output_obj = kadet_module.main(input_params).to_dict()
  File "/src/components/generators/kubernetes/__init__.py", line 799, in main
    return globals()[function](input_params)
  File "/src/components/generators/kubernetes/__init__.py", line 735, in generate_manifests
    config_maps = GenerateConfigMaps(name=name, component=component).root
  File "/opt/venv/lib/python3.7/site-packages/kapitan/inputs/kadet.py", line 188, in __init__
    self.body()
  File "/src/components/generators/kubernetes/__init__.py", line 541, in body
    component.config_maps.items()]
  File "/src/components/generators/kubernetes/__init__.py", line 540, in <listcomp>
    self.root = [ConfigMap(name=name, config=config, component=component) for config_name, config in
  File "/opt/venv/lib/python3.7/site-packages/kapitan/inputs/kadet.py", line 188, in __init__
    self.body()
  File "/src/components/generators/kubernetes/__init__.py", line 143, in body
    for key, config_spec in config.data.items():
AttributeError: 'NoneType' object has no attribute 'data'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/kapitan/targets.py", line 136, in compile_targets
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/opt/venv/lib/python3.7/site-packages/kapitan/targets.py", line 136, in <listcomp>
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
AttributeError: 'NoneType' object has no attribute 'data'


'NoneType' object has no attribute 'data'

```

**Comment by ademariag** [comment]
I think the code is correct to crash, because the component is malformed. 
Why would you expect them to be ignored? Do you have a use case mind?

I would suggest just to crash "better"

```
  File "/Users/ademaria/synthace/kapitan-reference/components/generators/kubernetes/__init__.py", line 537, in body
    raise Exception(f"{config_name} for component {name}: configuration cannot be empty!")
Exception: config for component echo-server: configuration cannot be empty!
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/kapitan/targets.py", line 136, in compile_targets
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/usr/local/lib/python3.9/site-packages/kapitan/targets.py", line 136, in <listcomp>
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
Exception: config for component echo-server: configuration cannot be empty!


config for component echo-server: configuration cannot be empty!
```
