### ISSUE TITLE
Can not compile minikube-nginx-kadet.yml example

### ISSUE THREAD

**Issue by fi-do** [kapicorp/kapitan#793]
**Describe the bug/feature**
Can not compile example minikube-nginx-kadet.yml

**To Reproduce**
```
git clone git@github.com:kapicorp/kapitan.git
cd kapitan/examples/kubernetes
kapitan compile

```

**Expected behavior**
Successfully compile targets.

**Screenshots**
```
Compiled labels (0.25s)
Compiled minikube-nginx-jsonnet (0.44s)
Compiled minikube-mysql (0.50s)
Compiled busybox (0.12s)
Compiled removal (0.00s)
Unknown (Non-Kapitan) Error occurred
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/fido/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/kapitan/targets.py", line 465, in compile_target
    input_compiler.compile_obj(comp_obj, ext_vars, **kwargs)
  File "/home/fido/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/kapitan/inputs/base.py", line 54, in compile_obj
    self.compile_input_path(input_path, comp_obj, ext_vars, **kwargs)
  File "/home/fido/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/kapitan/inputs/base.py", line 76, in compile_input_path
    **kwargs,
  File "/home/fido/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/kapitan/inputs/kadet.py", line 122, in compile_file
    output_obj = kadet_module.main().to_dict()
AttributeError: 'dict' object has no attribute 'to_dict'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fido/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/kapitan/targets.py", line 136, in compile_targets
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/home/fido/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/kapitan/targets.py", line 136, in <listcomp>
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
AttributeError: 'dict' object has no attribute 'to_dict'

```

** If it's a bug (please complete the following information):**
 - `python --version`: 3.7.5
 - `pip3 --version`:  21.3.1
 - `kapitan --version`: 0.29.5
 - `Are you using pyenv or virtualenv?`: venv

**Additional context**
I was learning to work with kapitan. When checking out the examples, I got this error with targets that are using kadet.

**Comment by ramaro** [comment]
Hey @fi-do thanks for reporting. Can you trying running with kapitan v0.30.0rc0? Running examples from master usually is synced with the latest release. More details on how to install it at the bottom of https://github.com/kapicorp/kapitan/releases/tag/v0.30.0-rc.0
Also, we've discontinued support for python 3.7,  so ideally you should upgrade to python 3.8, at minimum.

I will attempt to reproduce this however. Thanks

**Comment by fi-do** [comment]
Hey @ramaro,
thanks for your fast reply. Upgrading to v0.30 solved my problem.
