### ISSUE TITLE
kapiten refs --update-targets fails with boto exception during decryption

### ISSUE THREAD

**Issue by deepbrook** [kapicorp/kapitan#823]
**Describe the bug/feature**
When I change the aws key in use for my inventory, I want `kapitan refs --update-targets` to compare the key used to encrypt the ref (stored in the ref file) with the currently configured kms key (set in `parameters.kapitan.secrets.awskms.key`), and if this differs, decrypt refs using the old key and re-encrypt it using the new key.

This behaviour would likely be useful for all other secret mechanisms used.

**Comment by deepbrook** [comment]
It looks like it does, but fails with an odd error:

```bash
🐟 ❯ kapitan refs --update-targets --target sandbox
Found credentials in shared credentials file: ~/.aws/credentials
Traceback (most recent call last):
  File "/home/deepbrook/.virtualenvs/eks/lib/python3.8/site-packages/kapitan/refs/secrets/awskms.py", line 132, in _decrypt
    response = awskms_obj().decrypt(CiphertextBlob=base64.b64decode(data))
  File "/home/deepbrook/.virtualenvs/eks/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/deepbrook/.virtualenvs/eks/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the Decrypt operation: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deepbrook/.virtualenvs/eks/bin/kapitan", line 8, in <module>
    sys.exit(main())
  File "/home/deepbrook/.virtualenvs/eks/lib/python3.8/site-packages/kapitan/cli.py", line 562, in main
    args.func(args)
  File "/home/deepbrook/.virtualenvs/eks/lib/python3.8/site-packages/kapitan/refs/cmd_parser.py", line 33, in handle_refs_command
    secret_update_validate(args, ref_controller)
  File "/home/deepbrook/.virtualenvs/eks/lib/python3.8/site-packages/kapitan/refs/cmd_parser.py", line 495, in secret_update_validate
    secret_obj.update_key(awskey)
  File "/home/deepbrook/.virtualenvs/eks/lib/python3.8/site-packages/kapitan/refs/secrets/awskms.py", line 87, in update_key
    data_dec = self.reveal()
  File "/home/deepbrook/.virtualenvs/eks/lib/python3.8/site-packages/kapitan/refs/secrets/awskms.py", line 77, in reveal
    return self._decrypt(ref_data)
  File "/home/deepbrook/.virtualenvs/eks/lib/python3.8/site-packages/kapitan/refs/secrets/awskms.py", line 138, in _decrypt
    raise AWSKMSError(e)
kapitan.refs.secrets.awskms.AWSKMSError: An error occurred (AccessDeniedException) when calling the Decrypt operation: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.
```

The encryption key is indeed updated as expected.

**Comment by deepbrook** [comment]
Both keys exist in the sanbox target's account.

**Comment by ademariag** [comment]
Looks like a permission problem to me. 

Can you please verify sure you have (at least) "decrypt" permission for the source key, and "encrypt" permission for the target key

**Comment by deepbrook** [comment]
Was a missing kms key grant.

I'll show myself out. 😅
