### ISSUE TITLE
Allow kadet inventory function to return a lazy inventory

### ISSUE THREAD

**Issue by ramaro** [kapicorp/kapitan#848]
Since the move to the external kadet package, the default inventory function is now strict e.g. if an attribute key is not found the root, it will raise KeyError.
This brings back the original 'lazy' behavior by allowing to call `inventory(lazy=True)` in the kadet input type

**Comment by Moep90** [comment]
Using 0.31.0rc0 I now get 

```python
$ kapitan compile
Rendered inventory (0.21s)
Unknown (Non-Kapitan) Error occurred
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python@3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/danny/.env3_kapitan/lib/python3.7/site-packages/kapitan-0.31.0rc0-py3.7.egg/kapitan/targets.py", line 466, in compile_target
    input_compiler.compile_obj(comp_obj, ext_vars, **kwargs)
  File "/home/danny/.env3_kapitan/lib/python3.7/site-packages/kapitan-0.31.0rc0-py3.7.egg/kapitan/inputs/base.py", line 56, in compile_obj
    self.compile_input_path(input_path, comp_obj, ext_vars, **kwargs)
  File "/home/danny/.env3_kapitan/lib/python3.7/site-packages/kapitan-0.31.0rc0-py3.7.egg/kapitan/inputs/base.py", line 78, in compile_input_path
    **kwargs,
  File "/home/danny/.env3_kapitan/lib/python3.7/site-packages/kapitan-0.31.0rc0-py3.7.egg/kapitan/inputs/kadet.py", line 129, in compile_file
    output_obj = kadet_module.main(input_params)
  File "/home/danny/gitlab-repos/kapitan-nexenio/lib/argocd/__init__.py", line 336, in main
    return globals()[function](input_params)
  File "/home/danny/gitlab-repos/kapitan-nexenio/lib/argocd/__init__.py", line 322, in generate_manifests
    argocd_project_manifests = generate_argocd_appproject(input_params)
  File "/home/danny/gitlab-repos/kapitan-nexenio/lib/argocd/__init__.py", line 285, in generate_argocd_appproject
    obj.root['{}/{}-project'.format(name, name)] += argocd_project
  File "box/box.py", line 286, in box.box.Box.__iadd__
box.exceptions.BoxTypeError: Box can only merge two boxes or a box and a dictionary.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/danny/.env3_kapitan/lib/python3.7/site-packages/kapitan-0.31.0rc0-py3.7.egg/kapitan/targets.py", line 134, in compile_targets
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/home/danny/.env3_kapitan/lib/python3.7/site-packages/kapitan-0.31.0rc0-py3.7.egg/kapitan/targets.py", line 134, in <listcomp>
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/home/linuxbrew/.linuxbrew/opt/python@3.7/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
box.exceptions.BoxTypeError: Box can only merge two boxes or a box and a dictionary.


Box can only merge two boxes or a box and a dictionary.
```

**Comment by ramaro** [comment]
@Moep90 is this using a particular version of generators?

**Comment by Moep90** [comment]
From my perspective it can be resolved.

Inventory is still more strict. But in a fair amount I guess.
Actions for `kapitan-reference` can be found here:
https://github.com/kapicorp/kapitan-reference/pull/127 --> Still not finished but this is just an effort question.

**Comment by ademariag** [comment]
Resolved
