### ISSUE TITLE
Kapitan error logging for unassigned K/V pair

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan#868]
**Describe the bug/feature**
Kapitan should log an empty key which has no assigned value and point the user to file and ultimativ to the wrong part of the code.

**To Reproduce**
1. kapitan compile

**Actual behavior**
```
$ kapitan compile -t myclass
Unknown (Non-Kapitan) Error occurred
Traceback (most recent call last):
  File "...../python3.10/site-packages/kapitan-0.31.0rc0-py3.10.egg/kapitan/targets.py", line 88, in compile_targets
    target_objs = load_target_inventory(inventory_path, updated_targets)
  File "...../python3.10/site-packages/kapitan-0.31.0rc0-py3.10.egg/kapitan/targets.py", line 370, in load_target_inventory
    target_obj["target_full_path"] = inv_target["__reclass__"]["node"].replace("./", "")
TypeError: 'NoneType' object does not support item assignment


'NoneType' object does not support item assignment
```

**Expected behavior**
Kapitan should print a warning or an error for the key which is not assigned.
Variant 1:
```
$ kapitan compile -t myclass
ERROR! parameters.kapitan has no assignement
```

Variant 2:
```
$ kapitan compile -t myclass
ERROR! In file "inventory/classes/myclass.yml"

parameters:
  kapitan: <-- has no assignement
```
or similar...

**Additional context**
My Classfile
```yaml
$ cat inventory/classes/myclass.yml

parameters:
  kapitan:
```

**Comment by Moep90** [comment]
closed by #870
