### ISSUE TITLE
kapitan fails with importerror

### ISSUE THREAD

**Issue by Almenon** [kapicorp/kapitan#952]
OS: Mac

```
➜  ~ pipx list
venvs are in /Users/calebparks/.local/pipx/venvs
apps are exposed on your $PATH at /Users/calebparks/.local/bin
   package kapitan 0.31.0, installed using Python 3.9.6
    - kapitan
```

```
➜  ~ kapitan -h
Traceback (most recent call last):
  File "/Users/almenon/.local/bin/kapitan", line 5, in <module>
    from kapitan.cli import main
  File "/Users/almenon/.local/pipx/venvs/kapitan/lib/python3.9/site-packages/kapitan/cli.py", line 23, in <module>
    from kapitan.inputs.jsonnet import jsonnet_file
  File "/Users/almenon/.local/pipx/venvs/kapitan/lib/python3.9/site-packages/kapitan/inputs/jsonnet.py", line 14, in <module>
    from kapitan.inputs.base import CompiledFile, InputType
  File "/Users/almenon/.local/pipx/venvs/kapitan/lib/python3.9/site-packages/kapitan/inputs/base.py", line 19, in <module>
    from kapitan.refs.base import Revealer
  File "/Users/almenon/.local/pipx/venvs/kapitan/lib/python3.9/site-packages/kapitan/refs/base.py", line 23, in <module>
    from kapitan.utils import PrettyDumper, list_all_paths
  File "/Users/almenon/.local/pipx/venvs/kapitan/lib/python3.9/site-packages/kapitan/utils.py", line 12, in <module>
    import magic
  File "/Users/almenon/.local/pipx/venvs/kapitan/lib/python3.9/site-packages/magic/__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
  File "/Users/almenon/.local/pipx/venvs/kapitan/lib/python3.9/site-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

Directions for installing libmagic should be added to the readme. I've created a PR for that: https://github.com/kapicorp/kapitan/pull/951

**Comment by MatteoVoges** [comment]
Closing, because it got fixed by #951
